DIR = ./mtree

DEP = ${DIR}/mtree.cpp ${DIR}/search.cpp  ${DIR}/sexton_swinbank.cpp ${DIR}/generate_points.cpp

main:
	g++ ./main.cpp ${DEP} -o bin
	./bin
	rm bin


BASURA = ${DIR}/ciaccia_patella.cpp


deb:
	g++ -g -D_GLIBCXX_DEBUG